-- -------------
--  Sequence
-- -------------
CREATE SEQUENCE PERSON_ID_SEQ START WITH 1 INCREMENT BY 10;
CREATE SEQUENCE ADDRESS_ID_SEQ START WITH 1 INCREMENT BY 10;
CREATE SEQUENCE PET_ID_SEQ START WITH 1 INCREMENT BY 10;
-- ------------
--  TABLE
-- ------------
CREATE TABLE PERSONS (
"PERSON_ID"  NUMBER(19)  PRIMARY KEY,
"FIRST_NAME" VARCHAR(50) NOT NULL,
"LAST_NAME"  VARCHAR(50) NOT NULL,
"DOB"        DATE        NULL,
"ADDRESS_ID" NUMBER(19)  NOT NULL
);

CREATE TABLE ADDRESS (
"ADDRESS_ID"  NUMBER(19)  PRIMARY KEY,
"STREET"      VARCHAR(50) NULL,
"CITY"        VARCHAR(50) NULL,
"STATE"       VARCHAR(50) NULL,
"ZIPCODE"     VARCHAR(20) NOT NULL
);

CREATE TABLE PETS (
"PET_ID"  NUMBER(19) PRIMARY KEY,
"NAME"    VARCHAR(50) NOT NULL,
"AGE"     NUMBER(2)   NOT NULL
);

CREATE TABLE PERSON_PET (
"PET_ID"   NUMBER(19) NOT NULL PRIMARY KEY,
"PERSON_ID"      NUMBER(19) NOT NULL
);

-- -----------------
-- Constraint
-- -----------------
ALTER TABLE PERSONS
  ADD CONSTRAINT FK_PERSONADD FOREIGN KEY(ADDRESS_ID)
  REFERENCES ADDRESS(ADDRESS_ID);

ALTER TABLE PERSONS
  ADD CONSTRAINT UC_PERSON UNIQUE(FIRST_NAME, LAST_NAME);

ALTER TABLE PERSON_PET
  ADD CONSTRAINT FK_PERSONPETPERSON FOREIGN KEY(PERSON_ID)
  REFERENCES PERSONS(PERSON_ID);

ALTER TABLE PERSON_PET
  ADD CONSTRAINT FK_PERSONPETPET FOREIGN KEY(PET_ID)
  REFERENCES PETS(PET_ID);
