INSERT INTO ADDRESS (ADDRESS_ID, STREET, CITY, STATE, ZIPCODE) VALUES (ADDRESS_ID_SEQ.NEXTVAL, 'CHOPINLAAN', 'GRONINGEN', 'GRONINGEN', '9874UI');

INSERT INTO PERSONS (PERSON_ID, FIRST_NAME, LAST_NAME, DOB, ADDRESS_ID) VALUES (PERSON_ID_SEQ.NEXTVAL, 'GOPI', 'CHELLIAH', '1982-05-24', (SELECT ADDRESS_ID FROM ADDRESS WHERE STREET ='CHOPINLAAN'));

INSERT INTO PETS (PET_ID, NAME, AGE) VALUES (PET_ID_SEQ.NEXTVAL, 'Sweetie', 5);
INSERT INTO PETS (PET_ID, NAME, AGE) VALUES (PET_ID_SEQ.NEXTVAL, 'Sweetie2', 5);